catalog_name: mlops_students
schema_name: mahajan134
pipeline_id: 5d52b992-0c14-4abe-a8d8-3880ad86fe93

dev:
  catalog_name: mlops_students
  schema_name: mahajan134
  pipeline_id: 5d52b992-0c14-4abe-a8d8-3880ad86fe93

prod:
  catalog_name: mlops_students
  schema_name: mahajan134
  pipeline_id: 5d52b992-0c14-4abe-a8d8-3880ad86fe93

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

ab_test:
  learning_rate_a: 0.02
  learning_rate_b: 0.02
  n_estimators: 1000
  max_depth_a: 6
  max_depth_b: 10

num_features:
  - fixed_acidity
  - volatile_acidity
  - citric_acid
  - residual_sugar
  - chlorides
  - free_sulfur_dioxide
  - total_sulfur_dioxide
  - density
  - pH
  - sulphates
  - alcohol

target: quality
